#!/usr/bin/env bash
# Script runs nginx as nginx but short and sweet
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
